### ISSUE TITLE
'dcos marathon groups add' error when dependencies defined

### ISSUE THREAD

**Issue by akerekes** [mesosphere/dcos-cli#219]
I'm testing marathon's application groups via dcos and created a sample json. When I'm posting it via curl to Marathons REST api, it is successfully started. However via dcos cli I get errors.

If I add a toplevel empty
```"apps": [ ]```
property into the json, then I get:
```RefResolutionError: Unresolvable JSON pointer: u'definitions/pathType'```

Without the ```apps``` property just a lengthy stacktrace.

This is the command I'm using:
```dcos marathon group add multi.json```

The json:
```
{
  "id": "/multi-test7",
  "groups": [ {
    "id": "/multi-test7/persistence",
    "apps": [ {
      "id": "/multi-test7/persistence/mongo",
      "cmd": "while [ true ] ; do echo 'Fake MongoDB server' ; sleep 5 ; done",
      "cpus": 0.1,
      "mem": 64.0,
      "instances": 1
    }]
  },{
    "id": "/multi-test7/persistence2",
    "apps": [ {
      "id": "/multi-test7/persistence2/mongo",
      "dependencies": ["/multi-test7/persistence/mongo"],
      "cmd": "while [ true ] ; do echo 'Fake MongoDB server' ; sleep 5 ; done",
      "cpus": 0.1,
      "mem": 64.0,
      "instances": 1
    }]
  } ]
}
```
After some testing it turned out that if I remove the ```dependencies``` property from the json, it will be posted successfully to Marathon via dcos cli.

**Comment by ConnorDoyle** [comment]
Just a clue @mgummelt: from the error the jsonschema ref might be missing a leading `#`.  Also we must be missing a test case for groups with dependencies!

@akerekes thanks for reporting this.

**Comment by mgummelt** [comment]
Hey @akerekes, thanks for the bug report.  Looks like our jsonschema was buggy.  Fix is in review.  This should be out when we push our next CLI version in ~1 week

**Comment by akerekes** [comment]
@mgummelt  Sounds good, thanks!

**Comment by ssk2** [comment]
@akerekes - could you see if this issue has been resolved and report back? We pushed a new version out yesterday (make sure to uninstall entirely before reinstalling, as per: https://docs.mesosphere.com/install/cli/). Thanks!

**Comment by ssk2** [comment]
Closing for now, please let us know if you're still seeing this issue.
