### ISSUE TITLE
User PATH variable being replaced on windows

### ISSUE THREAD

**Issue by F21** [mesosphere/dcos-cli#227]
I am installing dcos-cli on Windows 8.1 64-bit using the installer script available here: https://downloads.mesosphere.io/dcos-cli/install.ps1 

When running the script, it replaces the user's PATH variable with the install path: `C:\Users\user\Desktop\dcos-cli\Scripts\`.

This means that the existing paths in the PATH variable is removed, which can break a few things.

It would be great if it's able to concatenate the dcos-cli path instead of replacing the path.

**Comment by ssk2** [comment]
@F21 - sorry for the slow response! We're on it, thanks for the issue :)

**Comment by ssk2** [comment]
Hey @F21  - can you try again (make sure you re-download the script, it may have changed)? We were unable to replicate this issue with the latest version of the script.

**Comment by F21** [comment]
@ssk2 I redownloaded the script from https://downloads.mesosphere.io/dcos-cli/install.ps1 and installed it, but my user PATH variable still got overwritten.

Note that it is not the system PATH variable that is overwritten, but the user's PATH variable.

**Comment by ssk2** [comment]
@F21 - ah, interesting. I'll double check!

**Comment by ssk2** [comment]
@F21 - you're right! We've fixed this in master, it'll be published to downloads.mesosphere.io when we next release. In the meantime, if you'd like to try the updated script, please grab (the script)[https://github.com/mesosphere/dcos-cli/blob/master/win_bin/install/install-dcos-cli.ps1] from here: https://raw.githubusercontent.com/mesosphere/dcos-cli/master/win_bin/install/install-dcos-cli.ps1.

Let us know if you run into any other problems. Closing this issue for now!
