### ISSUE TITLE
Security at DCOS and dcos-cli

### ISSUE THREAD

**Issue by Y4Rv1K** [mesosphere/dcos-cli#248]
Now we revised dcos/dcos-cli code  to discover security implemented into dcos and actually we didn’t find a lot. We see OAuth [implementation](https://github.com/mesosphere/dcos-cli/blob/778a0f1a0042c7badbdaa60afcf78fbcc48af4fa/dcos/auth.py) hardcoded into dcos cli. 

So I just wondering about your strategy about security. 
* What security elements will be implemented into DCOS? 
* What approaches will be used? 
* Are you planing to implement account management (Identity, Authorisation, Policy, Audit)?

**Comment by ssk2** [comment]
Hey @Y4Rv1K - this is more of a DCOS question than a DCOS CLI question. For now we use OAuth to support analytics and integration with our Mesosphere authentication service. 

We're still in the process of defining and documenting our security architecture for DCOS so I don't have many details to share with you currently. I suggest checking in with us on Slack (http://chat.mesosphere.com) at some point in the next few weeks!
