### ISSUE TITLE
Update Tests to Run Against DCOS Cluster

### ISSUE THREAD

**Issue by gabrielhartmann** [mesosphere/dcos-cli#295]
I believe that current tests only run against Mesos clusters with Marathon running.  I do not believe they actually run against DCOS clusters.  The test infrastructure for the dcos-cli tests needs to provision a DCOS cluster.

**Comment by jsancio** [comment]
It runs against a Vagrant VM generated from the DCOS Image.

**Comment by gabrielhartmann** [comment]
Then tests are not appropriately setting the dcos.core_url, or something else is going wrong.  http://<dcos.cor_url>/metadata does not return the correct information in the test context.  Some issue should be used to track this.  Either this one should be modified for clarity or a new one should be created.

**Comment by gabrielhartmann** [comment]
ssh to DCOS nodes is disabled by design
