### ISSUE TITLE
Provide printing task log to subcommands

### ISSUE THREAD

**Issue by tnachen** [mesosphere/dcos-cli#303]
Currently dcos-cli supports service log, but similiarly will be great to support task logs especially for subcommands.

A use case that this is great for is Spark, as the results of the Spark job is in the stdout/stderr and it's not easy to get the results from Mesos UI due to DCOS making slaves private.

Will be nice that we can just do "dcos spark log <driver-id>" which then call a library function from dcos package.

**Comment by jsancio** [comment]
@tnachen We have `dcos task log` does that solve your problem? See `dcos task --help`

**Comment by jsancio** [comment]
cc @mgummelt

**Comment by mgummelt** [comment]
`dcos task log`
