### ISSUE TITLE
dcos marathon app add doesn't return bad request message

### ISSUE THREAD

**Issue by tnachen** [mesosphere/dcos-cli#308]
When I add a app with "dcos marathon app add" and a json, if marathon returns a 400 with a message saying why the json definition is bad, all I see from the terminal is 400 Bad Request. So for a user to figure out what's wrong they still need to curl themselves to marathon to get the exact error message.

We should print out the response body so users can fix their json def.

**Comment by ssk2** [comment]
@tnachen - Can you share the bad JSON with us so we can replicate?

**Comment by tnachen** [comment]
I tried something like:
{ 
    "id": "/test",
    "cmd": "ls",
    "cpu": 1.0,
    "mem": 128.0,
    "container": {
        "type": "DOCKER",
        "docker": {
          "image": "busybox",
          "network": "host"
         }
    }
}

I have to curl to find out my network "host" needs to be upper cased "HOST" (which I think we should just upper case for folks..)

**Comment by ssk2** [comment]
@tamarrow - can you replicate this and create a JIRA for it? We'll fix this next sprint.

**Comment by tamarrow** [comment]
This has been fixed.
