### ISSUE TITLE
config set core.mesos_master_url to a zookeeper URI

### ISSUE THREAD

**Issue by michiroth** [mesosphere/dcos-cli#316]
Hi all,
I'm using just the CLI without a full DCOS.
I want to set the core.mesos_master_url to a zk URI which is permitted. Is this setting only available with a full DCOS instance or am I missing something? A master failover is not really covered with the hardcoding of a mesos master URI.
Many greets 
Michael

**Comment by ssk2** [comment]
@michiroth - what error message do you get when attempting to set the URL?

**Comment by michiroth** [comment]
@ssk2 - Error: '192.168.178.111:2181/mesos' does not match '^(?:(?:https?)://)(?:(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\\.?)+(?:[a-zA-Z]{2,6}\\.?|[a-zA-Z0-9-]{2,}\\.?)?|\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})(?::\\d+)?(?:/?|[/?]\\S+)$'
Path: core.mesos_master_url
Value: "192.168.178.111:2181/mesos"

**Comment by ssk2** [comment]
@michiroth - ah that's annoying. Can you try setting it manually in your .dcos/dcos.toml file?

**Comment by michiroth** [comment]
@ssk2 - Just setting core.mesos_master_url leads after dcos node to:

Traceback (most recent call last):
  File "/home/mroth/dcos/bin/dcos-node", line 11, in <module>
    sys.exit(main())
  File "/home/mroth/dcos/local/lib/python2.7/site-packages/dcoscli/node/main.py", line 40, in main
    return _main()
  File "/home/mroth/dcos/local/lib/python2.7/site-packages/dcoscli/node/main.py", line 53, in _main
    return cmds.execute(_cmds(), args)
  File "/home/mroth/dcos/local/lib/python2.7/site-packages/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/home/mroth/dcos/local/lib/python2.7/site-packages/dcoscli/node/main.py", line 108, in _list
    slaves = client.get_state_summary()['slaves']
  File "/home/mroth/dcos/local/lib/python2.7/site-packages/dcos/mesos.py", line 115, in get_state_summary
    return http.get(url, timeout=self._timeout).json()
  File "/home/mroth/dcos/local/lib/python2.7/site-packages/dcos/http.py", line 133, in get
    return request('get', url, to_exception=to_exception, **kwargs)
  File "/home/mroth/dcos/local/lib/python2.7/site-packages/dcos/util.py", line 485, in timer
    return fn(*args, **kwargs)
  File "/home/mroth/dcos/local/lib/python2.7/site-packages/dcos/http.py", line 96, in request
    raise to_exception(ex)
requests.exceptions.MissingSchema: Invalid URL 'master/state-summary': No schema supplied. Perhaps you meant http://master/state-summary?

**Comment by ssk2** [comment]
@michiroth - I've dug into this a little more. It looks like we haven't implemented ZooKeeper resolution at the moment. Typically when setting the Mesos master URI to a list of ZooKeeper nodes, the application will perform a lookup to find the hostname of the currently leading master. 

For DCOS clusters, we use the DCOS reverse proxy to reach the leading master, so unfortunately this functionality is only missing on raw Mesos clusters.

I'll create an internal issue for this but we're working on some other new functionality at the moment so it might take some time for us to get to it! We're, of course, happy to accept any pull requests with this functionality.

**Comment by michiroth** [comment]
@ssk2 - Kinda thought that :)
Unfortunately i haven't got a on-prem DCOS trial yet so the only way to go was to install the raw DCOS CLI. May u can have a look where my request stuck ;) But as stated with the raw CLI there may be some functionality missing like tada this one. I'll give it a try if I can allocate some time. Many thanks for the info in the meantime Sunil.
