### ISSUE TITLE
dcos package install gives incorrect message when installing a service that's already running

### ISSUE THREAD

**Issue by tnachen** [mesosphere/dcos-cli#333]
When spark is running on marathon, and running dcos package install spark again, it shows:

Installing Marathon app for package [spark] version [1.4.1]
App or group is locked by one or more deployments. Override with --force.

**Comment by mgummelt** [comment]
yea, I just introduced this.  will fix.  thanks

**Comment by jsancio** [comment]
@mgummelt @tnachen Did we fix this?

**Comment by ssk2** [comment]
@jsancio looks like we haven't. @mgummelt added this error message here: https://github.com/mesosphere/dcos-cli/commit/252bb02b3cc5cbdcd1eab5329ad3442f3a06cbca

Whereas previously we would show a generic "Error while fetching" method if the user attempted to install a package that had already been installed, now we show the full error message. I think we need might need to add a check to see if an app of that name already exists at the beginning here: https://github.com/mesosphere/dcos-cli/blob/master/cli/dcoscli/package/main.py#L308

**Comment by ssk2** [comment]
I've filed this in JIRA: https://mesosphere.atlassian.net/browse/DCOS-3821. Closing this issue for now.
