### ISSUE TITLE
Suggest use prompt-toolkit in dcos-cli

### ISSUE THREAD

**Issue by haosdent** [mesosphere/dcos-cli#334]
Hello, I found you could use https://github.com/jonathanslenders/python-prompt-toolkit to make dcos-cli more convenient.

**Comment by jsancio** [comment]
Nice. Thanks for the suggestion. Are there specific use cases or issues that you had in mind when you suggest this?

**Comment by haosdent** [comment]
No, I just with dcos become better. Let me close this issue.

**Comment by haosdent** [comment]
[wharfee](http://wharfee.com/) use this one to implement more convenient docker client.
