### ISSUE TITLE
Not a successor to mesos-cli and assumes DCOS + mesosphere.com account

### ISSUE THREAD

**Issue by drewrobb** [mesosphere/dcos-cli#338]
The deprecation notice at https://github.com/mesosphere/mesos-cli leads here. This project  is not usable as a replacement for mesos-cli. In particular, it asks for a mesosphere.com account and assumes the use of DCOS (no longer supports vanilla mesos).

**Comment by ssk2** [comment]
Hey [~drewrobb] - we still support vanilla Mesos, please see the README: https://github.com/mesosphere/dcos-cli#using-the-cli-without-dcos

As for using a Mesosphere.com account, you can easily skip that step and not enter a verification code when signing up, it'll still work fine.

Is there anything else that makes this unusable?

**Comment by drewrobb** [comment]
Hey, thanks for the fast response. I had followed those steps myself previously. Being asked for a mesosphere.com account by default even if that step is optional is not exactly the best user experience, but I'm mostly deterred by the README notice: 

    Note that the DCOS CLI has tight integration with DCOS and certain functionality may not work as expected or at all when using it directly with Mesos and Marathon.

Given that notice, I didn't see much point in trying to contribute to this project or report a specific vanilla mesos related bug. 

The particular feature I was looking for to work as a replacement for mesos-cli is file tailing / logs. node/service/task show up correctly, but `task log [taskID] [file]` expects a dcos_url when I haven't configured one. There is a TODO already marked for the issue I'm encountering: https://github.com/mesosphere/dcos-cli/blob/682dd06c5a50b0fa4430a314c629055f0b9f0a55/dcos/mesos.py#L70.

**Comment by ssk2** [comment]
Thanks for the feedback! I'll see if we can clarify the messaging there (re: Mesosphere account) and get that TODO addressed.

**Comment by mgummelt** [comment]
@drewrobb: I'll fix that TODO ASAP.  As for dcos-cli working with mesos, we do support vanilla mesos/marathon (bugs like this notwithstanding, obviously).  That "tight integration" message means that there are features of the CLI that will not work with mesos, because they simply don't exist in mesos (e.g. any `dcos package` command).  However, any mesos-level functionality should work with raw mesos as well.

So let us know if there's anything you'd like to see in this CLI to help you run your mesos cluster.

**Comment by drewrobb** [comment]
Thanks @mgummelt, I appreciate it. Totally wouldn't expect `dcos package` to work :)

**Comment by mgummelt** [comment]
Fixed in #343 

merged to master now

Thanks for the report @drewrobb
