### ISSUE TITLE
`dcos marathon group update` does nothing

### ISSUE THREAD

**Issue by flungo** [mesosphere/dcos-cli#350]
I am not sure if this is a case of marathon hasn't yet implemented group update or if the dcos CLI is doing it wrong but I get no error and yet nothing changes on marathon. Either way a change should be made to the CLI either informing that the feature is not yet supported or being fixed to work as expected.

If this should be working, let me know and I will try to make a simple marathon group to be able to reproduce.

Thanks in advance.

**Comment by tamarrow** [comment]
This should work. Could you give me an example of when it doesn't work? Thanks!

**Comment by Arkan** [comment]
Same issue here.
I created a group with two apps with `dcos marathon group add myapp.json `
Then when I wanted to deploy changes I tried to do:
```
dcos marathon group update myapp < myapp.json
Created deployment 2fe9b5d5-bb29-488e-b041-2a29349ad20f
```

But nothing happens ... Any idea?

**Comment by Arkan** [comment]
Any update on this?

**Comment by tamarrow** [comment]
The `group update` command should work. For example:
```
$ cat test.json
{
    "groups": [
        {
            "apps": [
                {
                    "id": "goodnight",
                    "cmd": "sleep 1",
                    "instances": 0
                },
                {
                    "id": "goodmorning",
                    "cmd": "sleep 1",
                    "instances": 0
                }
            ],
            "id": "sleep"
        }
    ],
    "id": "test-group"
}

$ dcos marathon group add < test.json

$ dcos marathon app list
ID                             MEM  CPUS  TASKS  HEALTH  DEPLOYMENT  CONTAINER  CMD
/test-group/sleep/goodmorning  128   1     0/0    ---       ---        mesos    sleep 1
/test-group/sleep/goodnight    128   1     0/0    ---       ---        mesos    sleep 1

$ cat test_update.json
{
    "apps": [
        {
            "cmd": "sleep 4",
            "id": "testupdate",
            "instances": 1
        }
    ]
}

$ dcos marathon group update test-group/sleep < test_update.json
Created deployment e858d8eb-1c29-462d-b099-f2a7f8bc9459

$ dcos marathon app list
ID                            MEM  CPUS  TASKS  HEALTH  DEPLOYMENT  CONTAINER  CMD
/test-group/sleep/testupdate  128   1     0/1    ---       ---        mesos    sleep 4
```

If the command still isn't working for you I'm happy to take a look if you can give me an example. Thanks!
