### ISSUE TITLE
App IDs and Group IDs may contain dots

### ISSUE THREAD

**Issue by kolloch** [mesosphere/dcos-cli#356]
Example: "/this/is/a.valid/app-or-group.id"

This regular expression forbids this:

https://github.com/mesosphere/dcos-cli/blob/master/cli/dcoscli/data/marathon-group-schema.json#L210

The regular expression which validates ID path segments in Marathon is here (the things between the slashes):

https://github.com/mesosphere/marathon/blob/releasing-0.11/src/main/scala/mesosphere/marathon/api/v2/ModelValidation.scala#L230

**Comment by jsancio** [comment]
@tamarrow Can you take a look at this?

**Comment by ssk2** [comment]
Bump @tamarrow

**Comment by jsancio** [comment]
This should be fixed with the latest version of the CLI.
