### ISSUE TITLE
CLI does not handle new Master election

### ISSUE THREAD

**Issue by clca** [mesosphere/dcos-cli#365]
if a new master is elected, dcos CLI reports an error because core.mesos_master_url does not point to the correct master.

**Comment by mgummelt** [comment]
We don't yet support ZK in core.mesos_master_url.  We will at some point.  If you instead use core.dcos_url with a DCOS cluster, the master connection will work as expected.

**Comment by ssk2** [comment]
I've filed this as a feature request internally @clca.
