### ISSUE TITLE
Allow for environment variables to overwrite default DCOS config

### ISSUE THREAD

**Issue by kiambogo** [mesosphere/dcos-cli#367]
I feel it would be beneficial to have the flexibility to allow for environment variables (or argument variables) to be used to override the default configuration TOML file. 

I have a need for this in the circumstance I'm in, where we have a default config that points to our production marathon URI and I would like to use the cli (wrapped in a propriatery docker container) to interface with a local marathon deploy on my machine. I realize that I could just download the vanilla CLI on my machine and have a config point to localhost, but it would be preferable to simply set environment variables and have those override the read config.

**Comment by ssk2** [comment]
Thanks for the suggestion @kiambogo! We'll track this internally - but it may be some time before we get to it. We're also working on our own Docker container which may help for your use case (you could perhaps extend it).

**Comment by tamarrow** [comment]
You can use the environment variable `DCOS_CONFIG` to point to whatever TOML file you want to use.
