### ISSUE TITLE
dcos kubectl not available?

### ISSUE THREAD

**Issue by pikeas** [mesosphere/dcos-cli#371]
Just did a `dcos package instal kubernetes`. According to http://docs.mesosphere.com/services/kubernetes, `dcos kubectl` should now be available as a sub-command.

It isn't.

**Comment by sttts** [comment]
@pikeas The latest package v1.0.6-v0.6.7 with the subcommand included was released just 4 days ago. Please try to reinstall the package in DCOS. After that `dcos kubectl` should just work.

**Comment by ariscn** [comment]
Great, I'll check it out later today! That means docs were prematurely updated at least a week prior to this feature being released?

**Comment by sttts** [comment]
@ariscn the doc changes were merged before the package, unfortunately. Sorry for the inconvenience.

**Comment by jsancio** [comment]
Closing this for now. Please re-open if you are still having issues. Thanks!
