### ISSUE TITLE
Shorten the SOURCE column for default repos

### ISSUE THREAD

**Issue by lloesche** [mesosphere/dcos-cli#383]
When working with `dcos package search` the SOURCE takes up too much space. Also there's strange newlines between package names.

I propose to shorten the SOURCE URLs for well known repositories to just the name and version. And only print full length URLs for custom repos. That way most users screen will look neat.
E.g. instead of repeating http://github.com/mesosphere/multiverse/archive/version-1.x.zip in every line just print `multiverse 1.x`.

<img width="894" alt="screen shot 2015-11-27 at 13 46 34" src="https://cloud.githubusercontent.com/assets/2124094/11441550/7956301c-950d-11e5-86b7-85ee0aa879ae.png">

**Comment by ssk2** [comment]
:+1:

**Comment by tamarrow** [comment]
we're removing sources from the table in the next release, so this won't be an issue anymore.
