### ISSUE TITLE
dcos-helloworld should be maintained better

### ISSUE THREAD

**Issue by sttts** [mesosphere/dcos-cli#385]
As a developer of a third party subcommand, I easily find https://github.com/mesosphere/dcos-helloworld and base by subcommand on it. I expect it to be in good shape and a good example how to write a good subcommand. 

In contrast it looks pretty much abandoned, e.g. tests do not work.

**Comment by jsancio** [comment]
Let's open this on that project. We need to add CI for it.

**Comment by sttts** [comment]
Opened two issues.

**Comment by sttts** [comment]
@jsancio Fixed tests and added CI: https://github.com/mesosphere/dcos-helloworld/pull/3

**Comment by jsancio** [comment]
Thanks!
