### ISSUE TITLE
dcos cli is looking for marathon with incorrect endpoint

### ISSUE THREAD

**Issue by anubhavsinha** [mesosphere/dcos-cli#388]
dcos cli is looking for marathon on port 80 instead of 8080 and path /marathon/v2/info instead of /v2/info

[ec2-user@ip-172-31-18-67 cli]$ dcos package install hdfs
In order for HDFS to start successfully, it requires a minimum of five nodes; each with at least 2 CPU shares and 8GB of RAM available for use by the HDFS Service.
Note that the service is alpha and there may be bugs, including possible data loss, incomplete features, incorrect documentation or other discrepancies.
Continue installing? [yes/no] yes
Installing Marathon app for package [hdfs] version [0.1.7]
URL [http://ip-172-31-23-64.ec2.internal/marathon/v2/info] is unreachable: HTTPConnectionPool(host='ip-172-31-23-64.ec2.internal', port=80): Max retries exceeded with url: /marathon/v2/info (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x32b6e10>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by jsancio** [comment]
Did you try setting the Marathon URL manually? `dcos config set marathon.url http://ip-address:80`.

The DCOS CLI assumes that it is talking to a DCOS cluster which includes a reverse router that sends requests to `/marathon/` to the internal Marathon endpoint. If you are not running a DCOS Cluster or have this reverse proxy you need to configure the CLI to point to the Marathon endpoint. You can do that with the command above.

FYI, you need to do the same thing for the Mesos Master: `dcos config set core.mesos_master_url http://ip-address:5050/`

**Comment by ssk2** [comment]
(See also the readme here: https://github.com/mesosphere/dcos-cli#using-the-cli-without-dcos)

**Comment by anubhavsinha** [comment]
@jsancio and @ssk2 Thanks. That helps.
