### ISSUE TITLE
After setting marathon.url dcos-package-install will install onto that Marathon instance

### ISSUE THREAD

**Issue by sttts** [mesosphere/dcos-cli#397]
After setting `marathon.url` in the dcos cli config (e.g. to access a marathon-user instance, compare https://github.com/mesosphere/dcos-cli/issues/396), the package command will use this as well. This is very confusing for the user.

In addition, services installed this way
- will not show up in the DCOS UI
- will not have a working admin router `/service/<framework-name>` endpoint.

**Comment by ssk2** [comment]
`marathon.url` and `core.dcos_url` are effectively setting the same property. It should be one or the other. That said, I don't know why services won't show up in the DCOS UI when installed onto a marathon-user instance.

**Comment by tamarrow** [comment]
If you specifically set `marathon.url` I would think it confusing if we use it for only some requests to marathon but not all. I don't know why it doesn't show up in the UI, could you file a bug against the UI team please?
