### ISSUE TITLE
add support for sources in search

### ISSUE THREAD

**Issue by tamarrow** [mesosphere/dcos-cli#421]

**Comment by jsancio** [comment]
@tamarrow I think I already added an issue for this: #420. Please double
check.
On Mon, Jan 25, 2016 at 22:49 tamarrow <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/dcos-cli/issues/421>.
>
-- 
José Armando García Sancio
Mesosphere
