### ISSUE TITLE
Remove legacy mode for package management

### ISSUE THREAD

**Issue by jsancio** [mesosphere/dcos-cli#447]
With the release of Cosmos we are only going to have support for the CLI to talk to Cosmos. So we should remove the following from the project.

- [x] Update the installer so that doesn't configuration options under the `package` subcommand when the latest is installed
- [x] Add new installer for legacy clusters that installes dcoscli<0.4.0 (need to verify that this version is spec is correct.
- [x] Remove all of the code dealing with legacy mode.
- [ ] Update documentation to so that it tells the user to use `0.3.x` for old clusters.
- [x] Latest CLI should discover that it is talking to a DCOS without Cosmos and instruct the user

**Comment by jsancio** [comment]
@tamarrow I updated the description.

**Comment by tamarrow** [comment]
everything is done except the documentation which has its own issue: #486
