### ISSUE TITLE
allow users to specify username + password in dcos_url for acs auth

### ISSUE THREAD

**Issue by tamarrow** [mesosphere/dcos-cli#475]

**Comment by tamarrow** [comment]
fixed by #474

**Comment by jsancio** [comment]
@tamarrow can you verify that we tested this and it works? Don't we have to parse `core.dcos_url` for this to work?

**Comment by tamarrow** [comment]
yep, it was basically a one line change, so I just added it to pr #474: https://github.com/mesosphere/dcos-cli/blob/master/dcos/http.py#L354
