### ISSUE TITLE
CLI doesn't recreate ~/.dcos on its own

### ISSUE THREAD

**Issue by nickbp** [mesosphere/dcos-cli#493]
nick@augustao:~/code/dcos-cli$ rm -rf ~/.dcos
nick@augustao:~/code/dcos-cli$ dcos config set core.email nick@mesosphere.io
Cannot create file [/home/nick/.dcos/dcos.toml]: [Errno 2] No such file or directory: '/home/nick/.dcos/dcos.toml'
nick@augustao:~/code/dcos-cli$ mkdir ~/.dcos
nick@augustao:~/code/dcos-cli$ dcos config set core.email nick@mesosphere.io
[core.email]: set to 'nick@mesosphere.io'

**Comment by tamarrow** [comment]
This is intentional, and talked about in #449, so I'm going to close this issue.
