### ISSUE TITLE
'dcos config set' could accept same format as 'dcos config show'

### ISSUE THREAD

**Issue by nickbp** [mesosphere/dcos-cli#494]
Given that 'dcos config show' gives values as 'key=value', it'd make sense for 'dcos config set key=value' to be allowed as well

**Comment by tamarrow** [comment]
We can't support `dcos config <set> <value>` and `dcos config <set>=<value>` using our parsing library (docopt). Given that this is a key part of the cli, it's not likely to be changed now.
