### ISSUE TITLE
Provide more precise error when querying cosmos against a nonexistent cluster 

### ISSUE THREAD

**Issue by nickbp** [mesosphere/dcos-cli#525]
Host that isn't running DCOS:

$ dcos config set core.dcos_url http://example.com
[core.dcos_url]: changed from 'http://pool-cae8-elasticl-1op07zlyuov6s-277026749.us-west-2.elb.amazonaws.com/' to 'http://example.com'
$ dcos package repo list
This version of the dcos-cli is unsupported for your DCOS cluster. Please use a dcos-cli version < 0.4.0 or upgrade your cluster to DCOS version >= 1.6.1
$ dcos package repo add foo http://foo.com
This version of the dcos-cli is unsupported for your DCOS cluster. Please use a dcos-cli version < 0.4.0 or upgrade your cluster to DCOS version >= 1.6.1

Host that doesn't resolve:

$ dcos config set core.dcos_url http://onstuhoesntuhoesunthoeusntoeusntoe
[core.dcos_url]: set to 'http://onstuhoesntuhoesunthoeusntoeusntoe'
$ dcos package repo list
This version of the dcos-cli is unsupported for your DCOS cluster. Please use a dcos-cli version < 0.4.0 or upgrade your cluster to DCOS version >= 1.6.1
$ dcos package repo add foo http://foo.com
This version of the dcos-cli is unsupported for your DCOS cluster. Please use a dcos-cli version < 0.4.0 or upgrade your cluster to DCOS version >= 1.6.1

Could either:
- Have more precise error detection in these cases, providing a different message when they occur.
- Failing that, add a clause to existing error message saying e.g. "or set core.dcos_url to something else"

**Comment by tamarrow** [comment]
At that point, we'd have to verify that the url is actually for a DCOS cluster.
