### ISSUE TITLE
Detect dcos_acs_token expiry and prompt to refresh credentials before performing intended operation

### ISSUE THREAD

**Issue by vishnu2kmohan** [mesosphere/dcos-cli#529]
Currently, if the `dcos_acs_token` has expired, we are required to perform a `dcos config unset dcos_acs_token` and re-attempt the original DCOS CLI operation.

Please detect and notify if the token has expired and gracefully recover by prompting for the credentials to make for a better user experience.

**Comment by tamarrow** [comment]
@jgehrcke What error are we expected to get if we request with an expired auth token?

**Comment by jgehrcke** [comment]
The corresponding HTTP status code will be a 401, and there is no indication for the precise reason in the response, for security reasons (it could be an invalid token signature, the token could be expired, and there could be various other subtle reasons -- all of this is purposely normalized into a 401).

The CLI can however inspect the token inspiration time on its own and act on it at will. Token inspection is easy. However, it involves a special flavor of base64-decoding which is provided by e.g. PyJWT (https://pypi.python.org/pypi/PyJWT/1.4.0).

The JWT has three sections, separated by a `.`. The second section is the payload section, which is a base64-encoded JSON-encoded structure which is required to contain the key `exp`, which encodes the expiration time as a string, representing the seconds since epoch (UTC). It's better to clarify this via code.

This is commented example code I have tested on Python 2.7 as well as 3.4:
```python

import json
import time


# https://pypi.python.org/pypi/PyJWT/1.4.0
from jwt.utils import base64url_decode
import requests


r = requests.post(
    "https://hostname/acs/api/v1/auth/login",
    json={"uid":"admin", "password":"foobar"}
    )


# Extract auth token from response body.
token = r.json()["token"]


# Obtain token's payload section.
payload_base64 = token.split(".")[1]

# Obtain payload dictionary:
# The payload section comes as a sequence of unicode code points,
# representing a base64-encoded JSON string. Reverse the operation:
# 1. Encode token into binary string via ASCII.
# 2. Decode into another binary string via base64.
# 3. Decode binary string into unicode string, assuming UTF-8 (the
#    default encoding for JSON).
# 4. Treat as JSON, decode into a dictionary.
payload = json.loads(base64url_decode(
    payload_base64.encode('ascii')).decode('utf-8'))


# Get current time and expiration time (UTC), in seconds since epoch.
expiration_time_utc = int(payload["exp"])
current_time_utc = time.time()


seconds_until_expiration = expiration_time_utc - current_time_utc


# Will the token expire within the next 5 minutes?
if seconds_until_expiration < 300:
    print("Will expire soon")
else:
    print("Valid for another %i s" % seconds_until_expiration)
```

Hope that helps!

**Comment by tamarrow** [comment]
This is being handled in #560

**Comment by jsancio** [comment]
> The corresponding HTTP status code will be a 401, and there is no indication for the precise reason in the response, for security reasons (it could be an invalid token signature, the token could be expired, and there could be various other subtle reasons -- all of this is purposely normalized into a 401).

> The CLI can however inspect the token inspiration time on its own and act on it at will. Token inspection is easy. However, it involves a special flavor of base64-decoding which is provided by e.g. PyJWT (https://pypi.python.org/pypi/PyJWT/1.4.0).

This is not clear to me why are there security concerns in adding this code to the server but not to the CLI?

**Comment by jgehrcke** [comment]
@jsancio I am not sure if I understand your question. Let me try to elaborate.

> This is not clear to me. Why are there security concerns in adding this code to the server 


How the server validates the token: a JWT has three sections: header, payload, signature. The server rightfully expects that the token has been signed using a secret that only it (the server) is aware of. The server cryptographically validates an incoming JWT by building a signature from the data-carrying part (header and payload section) and a secret key. It then matches the resulting signature with the signature presented in the token. If they do not match, the token has been tampered with. If they match, the server verifies that the token has not expired (by looking into its header, using about the approach I've shown above). I hope this explains that such code actually *is* executed server-side.

Now, with the argument of least information exposure, only a fully valid token leads to the request being authenticated. If no authentication token is presented in the request or if there is one but it is invalid in any way, it is responded to with a 401. This is predictable and correct behavior.

> but not to the CLI?

In contrast, the client has no way to cryptographically verify that the token has actually been issued by the server. Still, the client can _voluntarily_ trust the information it finds in the token and can act on it. This does not present a security hole.
