### ISSUE TITLE
how to install specific dcos-cli version without build from source code

### ISSUE THREAD

**Issue by adolphlwq** [mesosphere/dcos-cli#531]

**Comment by tamarrow** [comment]
Hi! When you install the cli from the bash install script, you can specify env variable `DCOS_CLI_VERSION` with the version you would like.

**Comment by adolphlwq** [comment]
OK,Thanks very much!@tamarrow

**Comment by adolphlwq** [comment]
Hi,I read mesosphere cli doc about [Environment](https://docs.mesosphere.com/administration/cli/environment-variables/),there are no docs about `DCOS_CLI_VERSION`,so I suggest that you'd better add it :smile:
