### ISSUE TITLE
'dcos package repo [add|list]' produce generic error when dcos_acs_token is invalid

### ISSUE THREAD

**Issue by nickbp** [mesosphere/dcos-cli#546]
Could've provided a less generic error up-front:

$ dcos config set core.dcos_url http://nick-wbrd-elasticl-hleacuxrp1be-4078661.us-west-2.elb.amazonaws.com/
[core.dcos_url]: changed from 'http://nick-fkoq-elasticl-j7d2p175pf7i-2114767423.us-west-2.elb.amazonaws.com/' to 'http://nick-wbrd-elasticl-hleacuxrp1be-4078661.us-west-2.elb.amazonaws.com/'

$ dcos package repo add --index=0 kafka https://github.com/mesosphere/universe/archive/kafka.zip
This version of the dcos-cli is unsupported for your DCOS cluster. Please use a dcos-cli version < 0.4.0 or upgrade your cluster to DCOS version >= 1.6.1

$ dcos package repo list
This version of the dcos-cli is unsupported for your DCOS cluster. Please use a dcos-cli version < 0.4.0 or upgrade your cluster to DCOS version >= 1.6.1

$ dcos config unset core.dcos_acs_token
Removed [core.dcos_acs_token]

$ dcos package repo list
nick-wbrd-elasticl-hleacuxrp1be-4078661.us-west-2.elb.amazonaws.com's username:

**Comment by rupakg** [comment]
@nickbp please upgrade to the latest version 0.4.2 of the dcos-cli. See release notes [here](https://github.com/mesosphere/dcos-cli/releases/tag/0.4.2).

**Comment by nickbp** [comment]
Aha yep that fixed it, thanks!
