### ISSUE TITLE
CLI trying to access master state information on master/state-summary

### ISSUE THREAD

**Issue by nandanrao** [mesosphere/dcos-cli#562]
On [line 126 of mesos.py](https://github.com/mesosphere/dcos-cli/blob/883d3bcd0290becdb767cf12c01b7b4a3f71c809/dcos/mesos.py#L126)

However the URL seems to have been moved to mesos/state-summary? The same applies for line 99 for state.json? I imagine all of this is just in flux and you probably know, happy to submit a PR of course if it's just cleanup. Causes the following error when trying to dcos node ssh --mesos-id=SLAVE_ID :

```
Error while fetching [http://CORE_URL/master/state-summary]: HTTP 404: Not Found
```

**Comment by jsancio** [comment]
@tamarrow Can you please investigate?

@nandanrao Which version of DCOS are you using?

**Comment by nandanrao** [comment]
@jsancio: 0.4.3

**Comment by tamarrow** [comment]
@nandanrao `0.4.3` is the dcos-cli version, can you also provide the version of your DCOS cluster please? Thanks!

**Comment by nandanrao** [comment]
v1.6.1

**Comment by tamarrow** [comment]
Did you set `core.mesos_master_url`? If you don't the "state-summary" we try to access is `http://DCOS_URL/mesos/master/state-summary` which I just tried, and worked for me: https://github.com/mesosphere/dcos-cli/blob/883d3bcd0290becdb767cf12c01b7b4a3f71c809/dcos/mesos.py#L57

Can you verify please? Thanks!

**Comment by nandanrao** [comment]
@tamarrow Damn, yep, that was it! Not sure how that was set, I must have set it accidentally when trying to set the core_url. Didn't notice that line, sorry about the Issue!
