### ISSUE TITLE
don't send to segment on called to "auth" subcommand

### ISSUE THREAD

**Issue by tamarrow** [mesosphere/dcos-cli#568]
Please answer the following questions before submitting your issue. Thanks!

### What version of the DCOS CLI are you using (`dcos --version`)?

0.4.3

### What version of DCOS are you using?

1.7.dev

### What operating system and version are you using?

osx

### What did you do?
If possible please provide a recipe for reproducing.

dcos auth logout
### What did you expect to see?

no output
### What did you see instead?
text to authenticated

**Comment by tamarrow** [comment]
unneeded after #570, but leaving as a remainder when we add tracking back in.

**Comment by jsancio** [comment]
I would just close this issue. It is not an issue after your PR so lets be optimistic and assume that it wont be an issue when we re-implement it. :smile:
