### ISSUE TITLE
Subcommand toml config subsections break authentication

### ISSUE THREAD

**Issue by sttts** [mesosphere/dcos-cli#580]
Start with a dcos.toml file without `dcos_acs_token` against a 1.7 cluster, but with a (empty) subsection named after a subcommand (like `[package]` or `[node]`).

The missing token will trigger a login prompt `Please go to the following link in your browser` in `_get_dcos_oauth_creds`. Entering a valid token will lead to `config.set_val("core.dcos_acs_token", token)` in `_get_dcos_auth`. Then `config.set_val` will try to check the schema of the old and the new config by calling `check_config(toml_config_pre, toml_config)`.

Now the subsection of the config, e.g. `[package]`, leads to a call of the subcommand `dcos package --config-schema`. Because `dcos_acs_token` is still not set, the subcommand with start another round of authentication.

This leads to an infinite authentication loop.

Obviously, subcommands should never try to authenticate with the cluster when called with the `--config-schema` flag.

**Comment by tamarrow** [comment]
Thanks for the thorough explanation! This is fixed by removing tracking, which is what is trying to authenticate. commit https://github.com/mesosphere/dcos-cli/commit/4a513f44923f7d577c4cbd55bef938afbf23e3b8

**Comment by sttts** [comment]
👍
